### PR TITLE
feat: update dependency

### LINKED ISSUE #46: `storage_withdraw` is not refunding storage balance
I’m not getting refunded after calling storage_withdraw but I can’t tell where things are going wrong :thinking_face:

When deploying, I call [storage_deposit](https://testnet.nearblocks.io/txns/5ASsZs68RWRX2qqsJDypTUtx2HTiy5L9JTqdqCuqv6Lc) on the file contract. When deleting the app, I delete storage to the point where the available balance is nearly equal to the total:
```
withdrawing balance {
  'gornt.testnet balance': '105.677779',
  'pfs1.testnet balance': '131.932608',
  'pfs1.testnet storage balance for gornt.testnet': '3.36484/3.36694'
}
```

Then I call [storage_withdraw](https://testnet.nearblocks.io/txns/7rS4GSWGARb8tqBDhUY6ibVU9cE63b7Kzz5tXvtoQBuN?tab=execution) and see that only a fraction of the available balance (0.18665N vs ~3.6N) is refunded. After this call, the deployer account actually loses Near instead of getting the original storage refunded:
```
balance withdrawn {
  'gornt.testnet balance': '105.676335',
  'gornt.testnet balance diff': '-0.001444',
  'pfs1.testnet balance': '131.933006',
  'pfs1.testnet balance diff': '0.000397',
  'pfs1.testnet storage balance for gornt.testnet': '0/0.0021'
}
```

Nothing sticks out as problematic in the method source, though it is worth mentioning I added a null check so that passing a null amount refunds the available funds. However, I was seeing the same behavior when specifying the amount when calling.

I think the key is understanding why storage_withdraw refunded 0.18665N; the transaction clearly went through but why is that the amount being refunded when the ~3.6 was being correctly deducted from the balance?

### PR DESCRIPTION
**Pull request by andy-haynes**
This PR updates the `near-sdk-js` version to `2.0.0`, enabling use of the `.build()` method to send transactions. I also went ahead and removed the `filestore-contract` package 🔪 

Fixes #46

### CODE REVIEW

**Comment by andy-haynes** [comment]
@race-of-sloths score 3

**Comment by andy-haynes** [comment]
@race-of-sloths 👋

**Comment by race-of-sloths** [comment]
@andy-haynes Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Weekly streak is on the road, smart strategy! Secure your streak with another PR!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/andy-haynes?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/andy-haynes?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/andy-haynes)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/andy-haynes)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by andy-haynes** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
### ❌ Self-scoring is not permitted. 
Let's keep it fair! 👍

**Comment by andy-haynes** [comment]
> ### ❌ Self-scoring is not permitted.
> Let's keep it fair! 👍

Yeah what would I know about it 🙄

**Comment by race-of-sloths** [comment]
### 🔄 The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! 🕰️

**Pull request merged**
